In [1]:
import numpy as np


def test_run():
	print np.array([(2,3,4),(5,6,7)])

if __name__ == "__main__":
	test_run()

[[2 3 4]
 [5 6 7]]


In [2]:
import numpy as np


def test_run():
	#print np.empty(5)
	#print np.empty((5,4))
	#print np.ones(5)
	#print np.ones((5,4))
	#print np.random.random((5,4))
	#print np.random.rand(5,4)
	#print np.random.normal(50,10,size=(2,3))
	#print np.random.randint(10)
	print np.random.randint(0,10,size=(2,3))
	

if __name__ == "__main__":
	test_run()


[[0 0 8]
 [8 3 5]]


In [3]:
import numpy as np


def test_run():
	#a = np.random.random((5,4))
	#print a.shape[0]
	#print a.shape[1]
	#print len(a.shape)		
	#print a.size
	#print a.dtype

	np.random.seed(693)
	a = np.random.randint(0,10,size=(5,4))
	print "Array:\n",a
	print "Sum of all elements:\n",a.sum()
	print "Sum of each row:\n",a.sum(axis=1)
	print "Sum of each column:\n",a.sum(axis=0)

	print "Max of each row:\n",a.max(axis=1)
	print "Min of each column:\n",a.min(axis=0)
	print "Mean of all elements:\n",a.mean()

if __name__ == "__main__":
	test_run()

Array:
[[2 0 5 1]
 [1 3 4 4]
 [9 2 9 1]
 [9 3 7 5]
 [4 7 0 3]]
Sum of all elements:
79
Sum of each row:
[ 8 12 21 24 14]
Sum of each column:
[25 15 25 14]
Max of each row:
[5 4 9 9 7]
Min of each column:
[1 0 0 1]
Mean of all elements:
3.95


In [4]:
import numpy as np


def get_max_index(a):
	"""Return the index of the maximum value in given 1D array."""
	# TODO: Your code here
	return np.argmax(a,axis=0)

def test_run():
	a = np.array([9, 6, 2, 3, 12, 14, 7, 10], dtype=np.int32)  # 32-bit integer array
	print "Array:", a
	
	# Find the maximum and its index in array
	print "Maximum value:", a.max()
	print "Index of max.:", get_max_index(a)


if __name__ == "__main__":
	test_run()

Array: [ 9  6  2  3 12 14  7 10]
Maximum value: 14
Index of max.: 5


In [5]:
import numpy as np



def test_run():
	a = np.random.randint(0,10,size=(2,3))
	print a
	print "----------------"
	print a[:,2]
	print "----------------"
	print a[0,:]
	print "----------------"
	b = a
	a[0,:] = 1
	print a
	print "----------------"
	b[:,2] = 9
	print b
	print "----------------"
	a[:,2] = [4,6]
	print a


if __name__ == "__main__":
	test_run()

[[4 7 9]
 [0 4 3]]
----------------
[9 3]
----------------
[4 7 9]
----------------
[[1 1 1]
 [0 4 3]]
----------------
[[1 1 9]
 [0 4 9]]
----------------
[[1 1 4]
 [0 4 6]]


In [6]:
import numpy as np



def test_run():
	a = np.random.randint(0,10,size=(5))
	print "1d array:\n",a
	indices = np.array([1,1,2,3])
	print "Array values using indices:\n",a[indices]
	
	print "-------------------"
	a = np.random.randint(0,10,size=(2,3))
	print "Array:\n",a
	mean = a.mean()
	print "Mean:\n",mean
	print "Elements less than mean:\n",a[a<mean]
	
	print "-------------------"
	a[a<mean] = mean
	print "Array with elements less than mean replaced by mean:\n",a

	print "-------------------"
	print "Multiply by 2:\n",a*2
	print "-------------------"
	print "Divide by 2:\n",a/2

	b = np.random.randint(10,20,size=(2,3))
	print "-------------------"
	print "a Array:\n",a
	print "-------------------"
	print "b Array:\n",b
	print "-------------------"
	print "Adding a+b:\n",a+b
	print "-------------------"
	print "Subtracting b-a:\n",b-a
	print "-------------------"
	print "Multiplying a*b:\n",a*b
	print "-------------------"
	print "Dividing b/a:\n",b/a
	print "-------------------"
	#print "Matrix multiplication a.b\n",np.dot(a,b)

if __name__ == "__main__":
	test_run()

1d array:
[1 3 5 7 5]
Array values using indices:
[3 3 5 7]
-------------------
Array:
[[1 5 6]
 [8 2 6]]
Mean:
4.66666666667
Elements less than mean:
[1 2]
-------------------
Array with elements less than mean replaced by mean:
[[4 5 6]
 [8 4 6]]
-------------------
Multiply by 2:
[[ 8 10 12]
 [16  8 12]]
-------------------
Divide by 2:
[[2 2 3]
 [4 2 3]]
-------------------
a Array:
[[4 5 6]
 [8 4 6]]
-------------------
b Array:
[[17 19 16]
 [13 19 19]]
-------------------
Adding a+b:
[[21 24 22]
 [21 23 25]]
-------------------
Subtracting b-a:
[[13 14 10]
 [ 5 15 13]]
-------------------
Multiplying a*b:
[[ 68  95  96]
 [104  76 114]]
-------------------
Dividing b/a:
[[4 3 2]
 [1 4 3]]
-------------------
